Small changes to compile under Windows
arhefner/Asm-02 pull request #18
Opened 2023-11-12 17:35 UTC by fourstix

Two small changes so the file can be compiled under windows.

1) Strings.h header is not available in Windows, so I moved the include statement into the Non-Windows else section if the #if defined(_WIN32) || defined(_WIN64)  statement in the header.h file.

2) The function localtime_r(X, Y)  is already defined in the Windows section of the header.h file, so the redefinition in asm.c causes a compile error.  I moved the definition out of asm.c into the Non-Windows #if defined(_WIN32) || defined(_WIN64)  . . . #else section in the header.h file.

With these two changes, I can successfully compile Asm/02 under Windows.

2023-11-12 18:30 UTC, arhefner requested changes

2023-11-12 18:30 UTC, arhefner commented on asm.c
I don't really like code in header files, and I'd prefer that both platforms use the same localtime_r, so I would suggest leaving this function in asm.c and removing the line:

#define localtime_r(X, Y) (localtime_s(Y, X))

from the Windows portion of the header file. I tested it out on Windows. It works fine and keeps more things consistent between the two OSes.

2023-11-12 18:35 UTC, fourstix commented on asm.c
Fair enough.  It's probably better to use the same function definition for both versions.  I'll update the code in the header and restore asm.c to the previous version and commit it to the PR.

2023-11-12 18:48 UTC, fourstix commented
Hi, I updated the fix to remove the definition for localtime_r in the header, so that the Windows code  uses the same definition as the Linux code.  I compiled it under Windows and it works fine.  The fix code is ready to review and merge.

2023-11-12 18:49 UTC, fourstix commented on asm.c
I made the change as requested.  I like that way better since the Windows version and Linux versions now use the same definition for localtime_r().

2023-11-13 02:04 UTC, arhefner approved these changes

2023-11-13 02:05 UTC, merged